export const DATA = 'DATA'
export const USER = 'USER'
export const SHOW_COMPLETED_EVENTS = 'SHOW_COMPLETED_EVENTS'
export const SELECTED_CARD_TAB = 'SELECTED_CARD_TAB'
export const TRIGGER = 'TRIGGER'
export const ASSIGNED_USERS = 'ASSIGNED_USERS'
